# Generated by Django 5.1 on 2024-11-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=60)),
                ('precio', models.PositiveSmallIntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
